### Task get api: fetch all the tasks
GET http://localhost:8000/api/v1/task


### Task post api
POST http://localhost:8000/api/v1/task
Content-Type: application/json

{
    "task": "PLaying football",
    "hr": 12
}


### Task delete api
DELETE  http://localhost:8000/api/v1/task