### root api
GET http://localhost:8000/

### Task get api: fetch all the tasks
GET http://localhost:8000/api/v1/task


### Task post api
POST http://localhost:8000/api/v1/task
Content-Type: application/json

{
    "task": "playing",
    "hr": 12
}


### Task delete api
DELETE  http://localhost:8000/api/v1/task/625e07de80e79d7f3ba76886

